# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages


notifications:
  email:
    on_success: change
    on_failure: change

# System dependencies for HTTP calling
r_binary_packages:
 - dplyr
 - DBI
 - RSQLite
 - RMySQL
 - RPostgreSQL
 - dbplyr
 